# Generated by Django 5.0.1 on 2025-06-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
